apiVersion: v1
kind: Secret
metadata:
  name: udagram-secrets
  namespace: udagram
type: Opaque
stringData:
  POSTGRES_USER: "udagram"
  POSTGRES_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  REDIS_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  JWT_SECRET: "CHANGE_ME_IN_PRODUCTION_USE_32_BYTES"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_BUCKET: "udagram-media"
